### ISSUE TITLE
Tests are broken after Webpack 3 upgrade - TODO new tests

### ISSUE THREAD

**Issue by vaaralav** [City-of-Helsinki/helerm-ui#104] opened 2017-12-05 07:52 UTC
Test [configuration](https://github.com/City-of-Helsinki/helerm-ui/blob/6cc781871262326450f0c6db9837018adb3a7b1e/config/karma.conf.js) fails like this:

```bash
❯ yarn test                                                         [09:42:26]
yarn run v1.3.2
$ better-npm-run test
running better-npm-run in /Users/vaaralav/Omni/helerm-ui
Executing script: test

to be executed: node ./node_modules/karma/bin/karma start config/karma.conf
  app:config Creating default configuration. +0ms
  app:config Looking for environment overrides for NODE_ENV "test". +41ms
  app:config No environment overrides found, defaults will be used. +3ms
  app:webpack:config Creating configuration. +411ms
  app:karma Creating configuration. +17ms
05 12 2017 09:42:29.383:ERROR [config]: Invalid config file!
  TypeError: Cannot read property 'concat' of undefined
```

Notice incorrect Wepback peer dependency for `karma-webpack-with-fast-source-maps`.

```bash
❯ nvm use lts/argon && yarn                             [09:40:43]
Now using node v4.8.6 (npm v3.10.10)
yarn install v1.3.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "karma-webpack-with-fast-source-maps > webpack-dev-middleware@1.10.0" has incorrect peer dependency "webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0".
[5/5] 📃  Building fresh packages...
✨  Done in 43.61s.
```

**Comment by Ta1Nur** [comment] 2018-01-25 07:57
@vaaralav Can you inform status and priority of this issue?

**Comment by vaaralav** [comment] 2018-01-25 08:46
The current status is that all tests for UI components (React) and UI state management (Redux) are disabled. The only test that is working now is the one for validations.

I tried to fix the test when I started working on the validation rules because I wanted to use test driven development method and have immediate feedback from automated tests if the validation rules were ok or not. I could get the test runner to start but I couldn't get UI tests to work. To save time and get back to working on the validation rules I commented out the tests that didn't work at all.

To me it seems like programmatic tests were not used much in this project. So maybe re-enabling the test cases isn't high priority thing. Or what do you think @jussiarpalahti ?

**Comment by jussiarpalahti** [comment] 2018-01-25 08:51
Hm. More test is always better than no test, unless test isn't maintained...

I can't say about tests working before, but I can confirm source maps had issues when I tried to debug IE problems.

**Comment by Ta1Nur** [comment] 2018-01-25 09:05
Thanks, we keep this open and try to get this sorted - if we get some time arranged from ui developers.

**Comment by jussiarpalahti** [comment] 2018-09-11 08:31
@adityagyawali As per your question on Slack, I can't exacly remember how the source map problem happens. IE should support source maps: https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/samples/dn255007(v=vs.85)#source_maps

As long as IE is supported browser for Helerm UI it is helpful to get source map support there too. Depends really on people doing the debugging. This issue seems to be about UI tests failing, though, which if still active I'd give higher priority.

**Comment by villeristi** [comment] 2018-09-11 16:57
Took a look at the issues and it's obvious that the [Redux Starter Kit](https://github.com/davezuko/react-redux-starter-kit) is full of legacy (test-runners, configuration, structure). The best solution for this would be to port the app to [Create React App](https://github.com/facebook/create-react-app) as it's actively maintained by Facebook & not going to go anywhere in the future. Even the RSK declares the following:

> This project was started at the advent of the Redux ecosystem, and was intended to help users get up and running quickly. Since then, tooling and best practices have evolved tremendously. In order to get the most modern experience possible, I recommend checking out something like create-react-app which is supported by many core React and Redux developers.

The same amount of time could be used to fix the tests or port the code directly to CRA (with Jest test-runner & slightly refactored tests). I'd go with the latter.

**Comment by Ta1Nur** [comment] 2018-09-12 08:52
@villeristi I agree that we make change CRA to more maintained solution. We may discuss priority later.

**Comment by Ta1Nur** [comment] 2018-09-12 09:06
Should we close this issue and write new one related to  [Create React App](https://github.com/facebook/create-react-app)

**Comment by Ta1Nur** [comment] 2018-09-13 13:57
OK - I close this.

**Closed by Ta1Nur** 2018-09-13 13:57 UTC
Labels: minor
